customhost = "employee.cjstsbv4obus.eu-north-1.rds.amazonaws.com"
customuser = "madhu29"
custompass = "MAmo2908#**"
customdb = "employee"
custombucket = "employbuck"
customregion = "us-east-2"
customtable = "employee"